# Generated by Django 3.2.8 on 2024-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
