# Generated by Django 3.2.8 on 2024-01-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
