# Generated by Django 3.2.8 on 2024-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=2500, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
