# Generated by Django 3.2.8 on 2024-01-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Stock'),
        ),
    ]
